apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-webserver
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/pv-webserver